### ISSUE TITLE
Multi-GPU Support for MSD trials

### ISSUE THREAD

**Issue by hungpham2017** [JoonhoLee-Group/ipie#268]
**Is your feature request related to a problem? Please describe.**
Yes, one of my colleagues experienced a bottleneck due to the current single-GPU implementation of ipie using SHCI trials. We're interested in exploring multi-GPU solutions. also, @linusjoonho had mentioned potential updates related to this feature in the past. It would be great if the developers could share any updates on this matter.

**Describe the solution you'd like**
A basic version of multi-GPU support would be sufficient for our needs.

Thank you!

**Comment by fdmalone** [comment]
There is no GPU support for MSD trials? How is this being run?

**Comment by fdmalone** [comment]
Also, what do you mean by multi-gpu support? Do you want to distribute the integrals among multiple gpus? Just run on multiple gpus (this should be supported for single determinant AFQMC through mpirun -np number_of_gpus). Something else?

To enable GPU support for MSD trials one would need to rewrite https://github.com/JoonhoLee-Group/ipie/blob/develop/ipie/estimators/kernels/cpu/wicks.py as an equivalent gpu/wicks.py and rewrite the kernels using cuda (via numba). It's also not clear to me that the other non-kernel routines would necessarily work out of the box on GPUs (anything with _wicks_ in the name). An alternative could be to ignore the kernels and use GPUs just for the dense linear algebra part with host-device transfers for the (cpu) kernels but I would worry that would lead to poor performance.

**Comment by yfhuang93** [comment]
Hi Fionn! This is Yifei here. Thanks for the prompt reply. I guess Hung thought that there is an internal MSD code with multi-GPU support because the memory could be a bottleneck in that case. So I guess he is asking about both the MSD as well as multi-GPU support. And you've answered both of them. Indeed I find the wicks part hard to GPU-ize. I guess it's a case-by-case thing depending on the problem size, in some cases the buildcont12 is more time-consuming and in others the wicks takes more time. 

For SD case, I feel memory can hardly be a problem so multi-GPU might not be necessary unless we tackle systems with nelectrons>100. Though I'd be interested to know whether "mpirun -np number_of_gpus" implements multi-GPU by just chunking the Hamiltonian and distributing the calculation to different devices. Appreciate your time.

**Comment by linusjoonho** [comment]
Hi Yifei, for SD we do support multi-GPU with chunking Hamiltonian.

**Comment by fdmalone** [comment]
The SD gpu code should work for both a chunked Hamiltonian (integrals are distributed among gpus on a node (say 8 or 16 gpus), and non-chunked (each gpu gets a copy of the integrals). The latter case will perform better but will be a bit more memory constrained.  I think the general advice would be to use as many walkers per GPU as you can get away with, certain intermediate tensors grow with the number of walkers so there is a limit naturally. But say you wanted to use 800 walkers and had 8 gpus you could set num_walkers = 100 and run like mpirun -np 8 python -u bin/ipie --gpu input.json (or similarly if using a more pythonic script).

We briefly investigated implementing a gpu variant of wicks a long time ago and at the time it wasn't 100% clear how much one would gain given the complications of porting the kernels. Not to say it's not worth doing but it can be tricky to get the best performance (it's why there are various variants of implementations in the SD case too)

**Comment by ywlds** [comment]
Overall, we try to optimize the code performance for multiple GPU with multiple dets. We are on the way to do this. Thank you for the comment. We will get back to you once we have more progress. @hungpham2017 @linusjoonho @fdmalone  maybe for now, we may close this issue.

**Comment by zohimchandani** [comment]
I would also appreciate support for MSD using multi-gpu multi node architectures. 

Any ideas on a timeline for this?

Thanks team. 

cc @davidev886
