### ISSUE TITLE
execution order between estimator and orthorgonalise in fp-AFQMC

### ISSUE THREAD

**Issue by jiangtong1000** [JoonhoLee-Group/ipie#317]
In the fp-AFQMC code, `orthogonalization` is currently performed prior to the propagation step, while the estimator is performed after propagation.

However, the estimator requires `phase` 
https://github.com/JoonhoLee-Group/ipie/blob/8eb3ce75eb82a05b553077fe8ddb4b8843837035/ipie/addons/free_projection/estimators/energy.py#L33-L40
which comes from the `ortho` step.
https://github.com/JoonhoLee-Group/ipie/blob/8eb3ce75eb82a05b553077fe8ddb4b8843837035/ipie/addons/free_projection/walkers/uhf_walkers.py#L52-L55

So, in fp-AFQMC, should we do `propagation -> ortho -> estimator` instead of `ortho -> propagation -> estimator`?

I was wondering if this potentially indicates a bug? @ankit76

**Comment by ankit76** [comment]
Hmm, orthogonalization shouldn't change any of the estimators, right? Because the scalar factor resulting from orthonormalization gets absorbed into the phase and the weight?

**Comment by jiangtong1000** [comment]
I agree. 
But when we compute the energy, we are using the `phase` belonging to those walkers at the orthogonalization step. Shouldn't we update the `phase` for the walkers used to estimate the energy?

**Comment by ankit76** [comment]
You mean update the phase during propagation? It doesn't need to be updated during propagation because the phase accumulated through propagation is included in the walker coefficient matrices. Orthogonalization takes out some of the phase information from the walker, which we can absorb into the walker matrices or keep track of separately as we do in the code.

**Comment by jiangtong1000** [comment]
oh I see! Thanks!
